services:
  db:
    container_name: "mysql_container"
    image: mysql:latest
    env_file:
      - "./db.env"
    ports:
      - "3305:3306"
  redis:
    container_name: "redis_container"
    image: redis:latest
    ports:
      - "6379:6379"