spring:
  application:
    name: LabSchedule
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: jdbc:mysql://${DB_URL}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        jdbc:
          time_zone=BRT
application:
  jwt:
    secret: ${JWT_SECRET}
  apis:
    mailgun:
      key: ${MAILGUN_KEY}
  email:
    domain: ${APPLICATION_EMAIL_DOMAIN}